seeder:
  file: ./seeder/seeder.rb
  disabled : false

parsers:
  - page_type: listings
    file: ./parsers/listings.rb
    disabled: false

  - page_type: books
    file: ./parsers/books.rb
    disabled: true